AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  openhouse-backend

  Backend SAM & Infrastructure

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs12.x

Resources:
  # Lambda Functions & API Events
  BuildingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: buildings/
      Handler: index.handler
      Events:
        Gateway:
          Type: Api
          Properties:
            Path: /buildings
            Method: ANY
  DepartmentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: departments/
      Handler: index.handler
      Events:
        Gateway:
          Type: Api
          Properties:
            Path: /departments
            Method: ANY

  # DynamoDB Tables
  BuildingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: OpenHouse-Buildings
      AttributeDefinitions:
        - AttributeName: UUID
          AttributeType: S # String
      KeySchema:
        - AttributeName: UUID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  DepartmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: OpenHouse-Departments
      AttributeDefinitions:
        - AttributeName: UUID
          AttributeType: S # String
      KeySchema:
        - AttributeName: UUID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
