name: Pull Request Checks

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Yarn Install
        run: yarn install
      - name: Run Tests
        run: yarn test --ci
  validate_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure PATH for Homebrew
        run: echo "::add-path::/home/linuxbrew/.linuxbrew/bin"
      - name: Install Homebrew & SAM CLI
        run: |
          sudo apt-get install build-essential curl file git
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
          brew --version
          brew tap aws/tap
          brew install aws-sam-cli
          sam --version
      - name: Validate Template
        run: sam validate
