name: Pull Request Checks

on:
  pull_request:
    branches-ignore:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Yarn Install
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Yarn Install
        run: yarn install
      - name: Run Tests
        run: yarn test --ci
